version: '3'
services:
  slowcore-postgres:
    image: "postgres:9.6-alpine"
    container_name: slowcore-postgres
    volumes:
      - v_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=slowcore
      - POSTGRES_USER=slowcore
      - POSTGRES_PASSWORD=slowcore
      - POSTGRES_HOST_AUTH_METHOD=trust

  slowcore-backend:
    build: .
    container_name: slowcore-backend
    stdin_open: true
    tty: true
    environment:
      - DB_SERVER=slowcore-postgres
      - DB_NAME=slowcore
      - DB_USER=slowcore
      - DB_PASSWORD=slowcore
      - API_PORT=8082
      - YT_DLP_PATH=binary/yt-dlp_linux
      - SOX_PATH=/usr/bin/sox
    ports:
      - 8082:8082
      - 5005:5005
      - 8888:8888
    links:
      - slowcore-postgres
    volumes:
      - v_files:/app/base/work

  slowcore-ui:
    build:
      context: ./frontend
      args:
        - VUE_APP_API_URL=http://localhost:8082
    container_name: slowcore-ui
    ports:
      - 8080:8080
    links:
      - slowcore-backend
volumes:
  v_db:
  v_files: